language: php

sudo: false

php:
  - 7.3
  - 7.4

install: composer install --prefer-source --no-interaction

script: bin/phpspec run -fpretty -v

after_script:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - php-coveralls.phar -v
